<?php

namespace Stadline\WSSESecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends EntityRepository
{
    public function findByLogin($login)
    {
        return $this->createQueryBuilder('p')
        ->where('p.login = :login')
        ->setParameter('login', $login);
    }
}
